# create basic configuration for docker compose using postgresql
version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_affiliate
    networks:
      - dev-network
  test-db:
    image: postgres:13
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_affiliate
    networks:
      - dev-network
networks:
  dev-network:
    driver: bridge

